on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: ilandemo1.azurecr.io
        username: ${{ secrets.acr_ilandemo1_username }}
        password: ${{ secrets.acr_ilandemo1_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t ilandemo1.azurecr.io/aksilandemo:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push ilandemo1.azurecr.io/aksilandemo:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksilandemo_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-ilan-demo | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-ilan-demo`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-ilan-demo
        container-registry-url: ilandemo1.azurecr.io
        container-registry-username: ${{ secrets.acr_ilandemo1_username }}
        container-registry-password: ${{ secrets.acr_ilandemo1_password }}
        secret-name: aksilandemodockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-ilan-demo
        manifests: |
          manifests/deployment-7.yml
          manifests/service-7.yml
        images: |
          ilandemo1.azurecr.io/aksilandemo:${{ github.sha }}
        imagepullsecrets: |
          aksilandemodockerauth
